### PR TITLE
Add field for editing target URL and introduce partial matching

### PR DESCRIPTION
**Pull request by jojosoft**
Another input field had to be added to the popup.
While doing this, I also tried to improve the UI's CSS.
It was at least needed to change flex-direction to colum.

### CODE REVIEW

**Comment by jojosoft** [comment]
By the way, great work! It's really the perfect addon for security-minded people who want to be able to quickly read through the source before installing and make sure that only their own code will be injected...

The only issue for me was that most of the time, the URLs will not match perfectly. There will almost always be some random session tokens or other GET parameters, or even subdomains like `server1.domain.tld`, `server2.domain.tld`, ...

Now you can adjust the URL it will store. In case you want different code e.g. for `domain.tld` and `domain.tld?param=true` it will still work, since we always search through all keys of the map and use the code for the longest matching URL.

**Comment by joeperpetua** [comment]
Seems good, thanks for the collaboration. Will merger and update in the Add-ons page, should be up in a few days.

**Comment by jojosoft** [comment]
You're welcome. Thanks, looking forward to use the updated add-on!
Und viel Freude noch beim Deutsch Lernen! 😁

**Comment by joeperpetua** [comment]
Dankeschön 😅 Also the update already got verified, should be available to update 👍👍

**Pull request merged**
